name: Playwright Java CI

on:
  workflow_dispatch:
    inputs:
      test_tag:
        description: 'Test tag to run'
        required: false
        default: 'regress'

env:
  TEST_TAG: ${{ github.event.inputs.test_tag || 'regress' }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests with tag
        env:
          TEST_TAG: ${{ env.TEST_TAG }}
        run: gradle clean -PtestTag=${{ env.TEST_TAG }}

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history